### ISSUE TITLE
Meta Description - Taxonomy Pages

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#155]
I just found out the meta descriptions on the career pages aren't working.  I tried researching the issue, but cannot figure out how to fix it. Can you please enable it at your earliest convenience?

**Comment by ehodul** [comment]
Fixed the issue, please review.

**Comment by ucem** [comment]
I can see it in payroll now.  What was the fix?

**Comment by ehodul** [comment]
I updated the code behind the career page, the function getting taxonomy
term meta data was not working as expected, I used another function that
works. I am not sure why the old function was not working, perhaps this
came with the metatag module update and it will be fixed in the new version
of metatag module.

---
Erika Hodul

Tel: 604 469 9363
Mobile: 604 339 8048
